// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.cbe.customer;

/**
 * Autogenerated enumeration CustomerAccountStatus.
 *
 * 
 */
public enum CustomerAccountStatus implements java.io.Serializable
{
    /**
     *  
     */
    ACTIVE,

    /**
     *  
     */
    INACTIVE;

    /**
     * CustomerAccountStatus constructor
     */
    private CustomerAccountStatus()
    {
    }

    /**
     * Return the CustomerAccountStatus from a string value
     * @return CustomerAccountStatus enum object
     */
    public static CustomerAccountStatus fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}