// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.cbe.customer;

/**
 * Autogenerated enumeration CustomerStatus.
 *
 * 
 */
public enum CustomerStatus implements java.io.Serializable
{
    /**
     *  
     */
    ACTIVE,

    /**
     *  
     */
    INACTIVE,

    /**
     *
     */
    AWAITING_AUTHORIZATION,

    /**
     *
     */
    BLOCKED_BY_CUSTOMER,

    /**
     *
     */
    BLOCKED_BY_FINANCE;

    /**
     * CustomerStatus constructor
     */
    private CustomerStatus()
    {
    }

    /**
     * Return the CustomerStatus from a string value
     * @return CustomerStatus enum object
     */
    public static CustomerStatus fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}