// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.common;

import javax.persistence.Column;

import org.hibernate.annotations.Index;

/**
 * Autogenerated POJO EJB class for Category containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "CATEGORY")
@javax.persistence.NamedQueries( {
        @javax.persistence.NamedQuery(name = "Category.findAll", query = "select category from Category AS category"),
        @javax.persistence.NamedQuery(name = "Category.findByType", query = "from Category c where c.categoryType.name=:type"),
        @javax.persistence.NamedQuery(name = "Category.findByName", query = "from Category cat where cat.name = :name") })
public class Category implements java.io.Serializable, Comparable < Category >
{
    
    private static final long serialVersionUID = 5715923687746276650L;
    
    // ----------- Attribute Definitions ------------
    
    private java.lang.String name;
    private java.lang.String description;
    private java.util.Map < java.util.Locale, java.lang.String > i18nName;
    private java.util.Map < java.util.Locale, java.lang.String > i18nDescription;
    private java.lang.Long id;
    private java.lang.Integer sortOrder;
    private java.lang.String externalId;
    
    // --------- Relationship Definitions -----------
    
    private ru.cti.oss.iptv.common.CategoryType categoryType;
    private ru.cti.oss.iptv.common.Rating rating;
    
    // ---- Manageable Display Attributes (Transient) -----
    
    // --------------- Constructors -----------------
    
    /**
     * Default empty constructor
     */
    public Category() {
    }
    
    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     */
    public Category(java.lang.String name, java.lang.String description) {
        setName(name);
        setDescription(description);
    }
    
    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param categoryType Value for the categoryType relation
     * @param rating Value for the rating relation
     */
    public Category(java.lang.String name, java.lang.String description, ru.cti.oss.iptv.common.CategoryType categoryType,
            ru.cti.oss.iptv.common.Rating rating) {
        setName(name);
        setDescription(description);
        
        setCategoryType(categoryType);
        setRating(rating);
    }
    
    // -------- Attribute Accessors ----------
    
    /**
     * Get the externalId property.
     * 
     * @return java.lang.String The value of externalId
     */
    @javax.persistence.Column(name = "EXTERNAL_ID", unique = false, nullable = true, insertable = true, updatable = true)
    public java.lang.String getExternalId() {
        return this.externalId;
    }
    
    /**
     * Set the externalId property.
     * @param value the new value
     */
    public void setExternalId(final java.lang.String value) {
        this.externalId = value;
    }
    
    /**
     * Get the name property.
     * 
     * @return java.lang.String The value of name
     */
    @javax.persistence.Column(name = "NAME", nullable = false, insertable = true, updatable = true)
    @Index(name = "name_index")
    public java.lang.String getName() {
        return name;
    }
    
    /**
     * Set the name property.
     * @param value the new value
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }
    
    /**
     * Get the description property.
     * 
     * @return java.lang.String The value of description
     */
    @javax.persistence.Column(name = "DESCRIPTION", insertable = true, updatable = true)
    @Index(name = "description_index")
    public java.lang.String getDescription() {
        return description;
    }
    
    /**
     * Set the description property.
     * @param value the new value
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }
    
    @org.hibernate.annotations.CollectionOfElements
    @org.hibernate.annotations.MapKeyManyToMany
    @javax.persistence.JoinTable(name = "category_i18n_name", joinColumns = { @javax.persistence.JoinColumn(name = "category_id", nullable = false) })
    @org.hibernate.annotations.MapKey(columns = @Column(name = "mapkey", nullable = false))
    public java.util.Map < java.util.Locale, java.lang.String > getI18nName() {
        return i18nName;
    }
    
    public void setI18nName(java.util.Map < java.util.Locale, java.lang.String > i18nName) {
        this.i18nName = i18nName;
    }
    
    @org.hibernate.annotations.CollectionOfElements
    @Column(name = "element", length=3800 , nullable=false)
    @org.hibernate.annotations.MapKeyManyToMany
    @javax.persistence.JoinTable(name = "category_i18n_description", joinColumns = { @javax.persistence.JoinColumn(name = "category_id", nullable = false) })
    @org.hibernate.annotations.MapKey(columns = @Column(name = "mapkey", nullable = false))
    public java.util.Map < java.util.Locale, java.lang.String > getI18nDescription() {
        return i18nDescription;
    }
    
    public void setI18nDescription(java.util.Map < java.util.Locale, java.lang.String > i18nDescription) {
        this.i18nDescription = i18nDescription;
    }
    
    /**
     * Get the id property.
     * 
     * @return java.lang.Long The value of id
     */
    @javax.persistence.Id
    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Column(name = "ID", nullable = false, insertable = true, updatable = true)
    @Index(name = "id_index")
    public java.lang.Long getId() {
        return id;
    }
    
    /**
     * Set the id property.
     * @param value the new value
     */
    public void setId(java.lang.Long value) {
        this.id = value;
    }
    
    /**
	 * @return the sortOrder
	 */
    @javax.persistence.Column(name = "SORT_ORDER", insertable = true, updatable = true)
	public java.lang.Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * @param sortOrder the sortOrder to set
	 */
	public void setSortOrder(java.lang.Integer sortOrder) {
		this.sortOrder = sortOrder;
	}
    
    // ------------- Relations ------------------
    
    

	/**
     * Get the categoryType
     *
     * @return ru.cti.oss.iptv.common.CategoryType
     */
    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "CATEGORYTYPE")
    @Index(name="category_type_index")
    public ru.cti.oss.iptv.common.CategoryType getCategoryType() {
        return this.categoryType;
    }
    
    

	/**
     * Set the categoryType
     *
     * @param categoryType
     */
    public void setCategoryType(ru.cti.oss.iptv.common.CategoryType categoryType) {
        this.categoryType = categoryType;
    }
    
    /**
     * Get the rating
     *
     * @return ru.cti.oss.iptv.common.Rating
     */
    @javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "RATING")
    @Index(name="rating_index")
    public ru.cti.oss.iptv.common.Rating getRating() {
        return this.rating;
    }
    
    /**
     * Set the rating
     *
     * @param rating
     */
    public void setRating(ru.cti.oss.iptv.common.Rating rating) {
        this.rating = rating;
    }
    
    // -------- Common Methods -----------
    
    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof Category)) {
            return false;
        }
        final Category that = (Category) object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId())) {
            return false;
        }
        return true;
    }
    
    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode() {
        int hashCode = 0;
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());
        
        return hashCode;
    }
    
    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Category(=");
        sb.append("name: ");
        sb.append(getName());
        sb.append(", description: ");
        sb.append(getDescription());
        sb.append(", id: ");
        sb.append(getId());
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * @see java.lang.Comparable#compareTo(T)
     */
    public int compareTo(Category o) {
        int cmp = 0;
        if (this.getId() != null) {
            cmp = this.getId().compareTo(o.getId());
        } else {
            if (this.getName() != null) {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(o.getName()));
            }
            if (this.getDescription() != null) {
                cmp = (cmp != 0 ? cmp : this.getDescription().compareTo(o.getDescription()));
            }
        }
        return cmp;
    }
}