// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.physical;

/**
 * Autogenerated POJO EJB class for Server containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "SERVER")
@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED)
@javax.persistence.NamedQuery(name = "Server.findAll", query = "select server from Server AS server order by id")
public class Server
    extends ru.cti.oss.cbe.resource.PhysicalResource
    implements java.io.Serializable
{

    private static final long serialVersionUID = 1036511201701030505L;

    // ----------- Attribute Definitions ------------

    private java.lang.String hostname;

    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public Server() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param availabilityStatus Value for the availabilityStatus property
     * @param hostname Value for the hostname property
     */
    public Server(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, ru.cti.oss.cbe.datatypes.AvailabilityStatus availabilityStatus, java.lang.String hostname)
    {
        super(name, description, status, availabilityStatus);
        setName(name);
        setDescription(description);
        setStatus(status);
        setAvailabilityStatus(availabilityStatus);
        setHostname(hostname);
    }



    // -------- Attribute Accessors ----------

    /**
     * Get the hostname property.
     * 
     * @return java.lang.String The value of hostname
     */
    	@javax.persistence.Column(name = "HOSTNAME", nullable = false, insertable = true, updatable = true)
    public java.lang.String getHostname()
    {
        return hostname;
    }

    /**
     * Set the hostname property.
     * @param value the new value
     */
    public void setHostname(java.lang.String value)
    {
        this.hostname = value;
    }


    // ------------- Relations ------------------

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Server))
        {
            return false;
        }
        final Server that = (Server)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("Server(=");
        sb.append(super.toString());
        sb.append("hostname: ");
        sb.append(getHostname());
        sb.append(")");
        return sb.toString();
    }

}