// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

/**
 * Autogenerated POJO EJB class for NpvrChannel containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 *
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "NPVR_CHANNEL")
@javax.persistence.NamedQueries
({
    @javax.persistence.NamedQuery(name = "NpvrChannel.findAll", query = "select npvrChannel from NpvrChannel AS npvrChannel"),
    @javax.persistence.NamedQuery(name = "NpvrChannel.findByStatus", query = "from NpvrChannel as npvrChannel where npvrChannel.status = :status"),
    @javax.persistence.NamedQuery(name = "NpvrChannel.findByBtvChannel", query = "select npvrChannel from NpvrChannel npvrChannel where npvrChannel.btvChannel.id=:btvChannelId"),
    @javax.persistence.NamedQuery(name = "NpvrChannel.loadCountActiveRecords", query = "select count(npvrChannel) from NpvrChannel npvrChannel, BtvChannel btvChannel where npvrChannel.btvChannel.id = :id and npvrChannel.status='ACTIVE'")
})
public class NpvrChannel
    extends ru.cti.oss.cbe.resource.LogicalResource
    implements java.io.Serializable
{

    private static final long serialVersionUID = 2562966350724536413L;

    // ----------- Attribute Definitions ------------

    private java.lang.Long storeTime;
    private java.lang.Long scheduleTime;
    private java.lang.Long storeRecordedTime;


    // --------- Relationship Definitions -----------

    private java.util.Set<ru.cti.oss.iptv.resource.physical.VideoServer> videoservers = new java.util.TreeSet<ru.cti.oss.iptv.resource.physical.VideoServer>();
    private ru.cti.oss.iptv.resource.logical.BtvChannel btvChannel;

    // ---- Manageable Display Attributes (Transient) -----


    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public NpvrChannel() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param storeTime Value for the storeTime property
     * @param scheduleTime Value for the scheduleTime property
     * @param storeRecordedTime Value for the storeRecordedTime property
     */
    public NpvrChannel(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, java.lang.Long storeTime, java.lang.Long scheduleTime)
    {
        super(name, description, status);
        setName(name);
        setDescription(description);
        setStatus(status);
        setStoreTime(storeTime);
        setScheduleTime(scheduleTime);
        setStoreRecordedTime(storeRecordedTime);
    }

    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param storeTime Value for the storeTime property
     * @param scheduleTime Value for the scheduleTime property
     * @param storeRecordedTime Value for the storeRecordedTime property
     * @param videoservers Value for the videoservers relation
     * @param btvChannel Value for the btvChannel relation
     */
    public NpvrChannel(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, java.lang.Long storeTime, java.lang.Long scheduleTime, java.util.Set<ru.cti.oss.iptv.resource.physical.VideoServer> videoservers, ru.cti.oss.iptv.resource.logical.BtvChannel btvChannel)
    {
        setName(name);
        setDescription(description);
        setStatus(status);
        setStoreTime(storeTime);
        setScheduleTime(scheduleTime);
        setStoreRecordedTime(storeRecordedTime);

        setVideoservers(videoservers);
        setBtvChannel(btvChannel);
    }


    // -------- Attribute Accessors ----------

    /**
     * Get the storeTime property.
     *
     * @return java.lang.Long The value of storeTime
     */
    	@javax.persistence.Column(name = "STORE_TIME", nullable = false, insertable = true, updatable = true)
    public java.lang.Long getStoreTime()
    {
        return storeTime;
    }

    /**
     * Set the storeTime property.
     * @param value the new value
     */
    public void setStoreTime(java.lang.Long value)
    {
        this.storeTime = value;
    }

    /**
     * Get the scheduleTime property.
     *
     * @return java.lang.Long The value of scheduleTime
     */
    	@javax.persistence.Column(name = "SCHEDULE_TIME", nullable = false, insertable = true, updatable = true)
    public java.lang.Long getScheduleTime()
    {
        return scheduleTime;
    }

    /**
     * Set the scheduleTime property.
     * @param value the new value
     */
    public void setScheduleTime(java.lang.Long value)
    {
        this.scheduleTime = value;
    }

    /**
     * Get the storeRecordedTime property.
     *
     * @return java.lang.Long The value of storeRecordedTime
     */
    	@javax.persistence.Column(name = "STORE_RECORDED_TIME", insertable = true, updatable = true)
    public java.lang.Long getStoreRecordedTime()
    {
        return storeRecordedTime;
    }

    /**
     * Set the storeRecordedTime property.
     * @param value the new value
     */
    public void setStoreRecordedTime(java.lang.Long value)
    {
        this.storeRecordedTime = value;
    }

    // ------------- Relations ------------------

    /**
     * Get the videoservers Collection
     *
     * @return java.util.Set<ru.cti.oss.iptv.resource.physical.VideoServer>
     */
    @javax.persistence.ManyToMany(fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinTable
    (
        name = "NPVR_CHANNELS2VIDEOSERVERS",
        joinColumns = {@javax.persistence.JoinColumn(name = "NPVR_CHANNEL_IDC", referencedColumnName = "ID")},
        inverseJoinColumns = {@javax.persistence.JoinColumn(name = "VIDEO_SERVER_IDC", referencedColumnName = "ID")}
    )
    public java.util.Set<ru.cti.oss.iptv.resource.physical.VideoServer> getVideoservers()
    {
        return this.videoservers;
    }

    /**
     * Set the videoservers
     *
     * @param videoservers
     */
    public void setVideoservers (java.util.Set<ru.cti.oss.iptv.resource.physical.VideoServer> videoservers)
    {
        this.videoservers = videoservers;
    }

    /**
     * Add VideoServer
     *
     * @param videoServer
     */

    public void addToVideoservers(ru.cti.oss.iptv.resource.physical.VideoServer videoServer)
    {
        if (videoServer == null ) return;
        this.getVideoservers().add(videoServer);
    }

    /**
     * Remove VideoServer
     *
     * @param videoServer
     */

    public void removeFromVideoservers (ru.cti.oss.iptv.resource.physical.VideoServer videoServer)
    {
        if (videoServer == null ) return;
        this.getVideoservers().remove(videoServer);
    }

    /**
     * Get the btvChannel
     *
     * @return ru.cti.oss.iptv.resource.logical.BtvChannel
     */
    @javax.persistence.OneToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "BTVCHANNEL")

    public ru.cti.oss.iptv.resource.logical.BtvChannel getBtvChannel()
    {
        return this.btvChannel;
    }

   /**
    * Set the btvChannel
    *
    * @param btvChannel
    */
    public void setBtvChannel(ru.cti.oss.iptv.resource.logical.BtvChannel btvChannel)
    {
        this.btvChannel = btvChannel;
    }

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof NpvrChannel))
        {
            return false;
        }
        final NpvrChannel that = (NpvrChannel)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("NpvrChannel(=");
        sb.append(super.toString());
        sb.append("storeTime: ");
        sb.append(getStoreTime());
        sb.append(", scheduleTime: ");
        sb.append(getScheduleTime());
        sb.append(", storeRecordedTime: ");
        sb.append(getStoreRecordedTime());
       sb.append(")");
        return sb.toString();
    }

}