// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

import javax.persistence.Transient;

import org.hibernate.annotations.Index;

/**
 * Autogenerated POJO EJB class for Program containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 *
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "PROGRAM")
@org.hibernate.annotations.BatchSize(size=20)
@javax.persistence.NamedQueries( {
        @javax.persistence.NamedQuery(name = "Program.findAll", query = "select program from Program AS program"),
        @javax.persistence.NamedQuery(name = "Program.findByChannel", query = "from Program p where p.channel.id = :channel order by p.timeFrame.startTime"),
        @javax.persistence.NamedQuery(name = "Program.findByTime", query = "from Program p where p.channel.id = :channel and :startTime between p.timeFrame.startTime and p.timeFrame.endTime "),
        
        @javax.persistence.NamedQuery(name = "Program.findByTimeFrame", 
        		query = "select p from Program p " +
        				"where p.channel.id = :channel " +
        				"and ( " +
        				"     (p.timeFrame.startTime between :startTime and :endTime or p.timeFrame.endTime between :startTime and :endTime) " +
        				"      or " +
        				"     (p.timeFrame.startTime <= :startTime and p.timeFrame.endTime >= :endTime ) " +
        				"   ) " +
        				"order by p.timeFrame.startTime"),
        				
        @javax.persistence.NamedQuery(name = "Program.findByTimeFrameSeverity", 
           		query = "select p from Program p " +
           				"where p.channel.id = :channel " +
           				"and ( " +
          				"     (p.timeFrame.startTime <= :startTime and p.timeFrame.endTime > :startTime) or " +
          				"     (p.timeFrame.startTime >= :startTime and p.timeFrame.startTime < :endTime) " +
           				"   ) " +
           				"order by p.timeFrame.startTime"),
        				
        @javax.persistence.NamedQuery(name = "Program.findProgramsByTimeFrameAndChannels", 
           		query = "select p from Program p " +
           				"where p.channel.id in (:ids) " +
           				"and ( " +
          				"     (p.timeFrame.startTime <= :startTime and p.timeFrame.endTime > :startTime) or " +
          				"     (p.timeFrame.startTime >= :startTime and p.timeFrame.startTime < :endTime) " +
           				"   ) " +
           				"order by p.channel.id , p.timeFrame.startTime"),
        				
        @javax.persistence.NamedQuery(name = "Program.findEpgOverDay", query = "from Program p where p.channel.id = :channel and "
                    + " p.timeFrame.startTime >= :startTime and  p.timeFrame.startTime <=:endTime  "
                    + "  order by p.timeFrame.startTime"),
        @javax.persistence.NamedQuery(name = "Program.findCurrentProgram", query = "from Program p where p.channel.id = :channel and  "
                + "(p.timeFrame.endTime  > :startTime) order by p.timeFrame.startTime"),
        @javax.persistence.NamedQuery(name = "Program.findOld", query = "from Program p where p.timeFrame.endTime <= :timeExpired"),
        @javax.persistence.NamedQuery(name = "Program.findCurrentEpg", query = "select p.channel.id, p.cachedName from Program p "
                + "where p.timeFrame.startTime <= :current_time  and p.timeFrame.endTime >= :current_time"),
        @javax.persistence.NamedQuery(name = "Program.findMinDurationCurrentEpg", query = "select  min(p.timeFrame.endTime) from Program p "
                + "where p.timeFrame.startTime <= :current_time  and p.timeFrame.endTime > :current_time"),
        @javax.persistence.NamedQuery(name = "Program.findFinishedRecordedPrograms", 
        		query = "select p from Program as p, MediaAsset ma " +
        				"left join p.mediaSources ms " +
        				"where ms member of MediaAsset " +
        					"and ms.id = ma.id " +
        					"and ms.status = 'PLANNED' " +
        					"and p.timeFrame.endTime <= current_timestamp()"),
        @javax.persistence.NamedQuery(name = "Program.findOldOrderedRecords",
        		query = "select pm from Program pm " +
        				"where id in ( " +
        					"select distinct(p.id) from Program as p " +
        					"join p.mediaSources ms " +
        					"where p.channel = :btvChannel " +
        						"and p.timeFrame.endTime <= :beginInterval)"),
        @javax.persistence.NamedQuery(name = "Program.findExpiredPrograms",
        		query = "select pm from Program pm " +
        				"where id in ( " +
        					"select distinct(p.id) from Program as p " +
        					"inner join p.mediaSources ms " +
        					"where p.channel = :btvChannel " +
        						"and p.timeFrame.endTime <= :beginInterval " +
        						"and p.id not in ( " +
        							"select distinct rec.program.id from NpvrRecord rec " + "))"),
        @javax.persistence.NamedQuery(name = "Program.findPendingProgramsForRecording",
        		query = "select p from Program p " +
        				"left join p.mediaSources ms " +
        					"where p.timeFrame.startTime >= :beginInterval " +
        						"and p.timeFrame.startTime <= :endInterval " +
        						"and p.channel = :btvChannel " +
        						"and ms is null"),
        @javax.persistence.NamedQuery(name = "Program.findPartlyPendingProgramsForRecording",
        		query = "select p from Program p, NpvrChannel nc " +
        				"inner join p.mediaSources ms " +
        					"where p.timeFrame.startTime >= :beginInterval " +
        					"and p.timeFrame.startTime <= :endInterval and p.channel = :btvChannel " +
        					"and p.channel = nc.btvChannel and ms member of MediaAsset and size(nc.videoservers) != size(ms.videoservers)")
        
        })
public class Program extends ru.cti.oss.iptv.resource.logical.MediaContent implements java.io.Serializable
{
    
    private static final long serialVersionUID = 3867052222600500139L;
    
    // ----------- Attribute Definitions ------------
    
    private ru.cti.oss.cbe.datatypes.TimePeriod timeFrame = new ru.cti.oss.cbe.datatypes.TimePeriod();
    private java.lang.Long duration;
    private java.lang.String imageUrl;
    private java.lang.String premiere;
    private java.lang.String credits;
    private java.lang.String episodeNumber;
    private java.lang.Boolean recordable;
    private java.lang.String cachedName;
    
    private String category;
    private String categoryCode;
    private String director;
    private String actor;
    private String presenter;
    private String ratingAdd;
    private String country;
    
    // --------- Relationship Definitions -----------
    
    private ru.cti.oss.iptv.resource.logical.BtvChannel channel;
    
    // ---- Manageable Display Attributes (Transient) -----
    
    // --------------- Constructors -----------------
    
    /**
     * Default empty constructor
     */
    public Program() {
    }
    
    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param timeFrame Value for the timeFrame property
     * @param duration Value for the duration property
     * @param imageUrl Value for the imageUrl property
     * @param premiere Value for the premiere property
     * @param credits Value for the credits property
     * @param episodeNumber Value for the episodeNumber property
     * @param recordable Value for the recordable property
     */
    public Program(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status,
            ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, java.lang.Long duration, java.lang.String imageUrl, java.lang.String premiere,
            java.lang.String credits, java.lang.String episodeNumber, java.lang.Boolean recordable) {
        super(name, description, status);
        setName(name);
        setDescription(description);
        setStatus(status);
        setTimeFrame(timeFrame);
        setDuration(duration);
        setImageUrl(imageUrl);
        setPremiere(premiere);
        setCredits(credits);
        setEpisodeNumber(episodeNumber);
        setRecordable(recordable);
    }
    
    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param timeFrame Value for the timeFrame property
     * @param duration Value for the duration property
     * @param imageUrl Value for the imageUrl property
     * @param premiere Value for the premiere property
     * @param credits Value for the credits property
     * @param episodeNumber Value for the episodeNumber property
     * @param recordable Value for the recordable property
     * @param channel Value for the channel relation
     */
    public Program(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status,
            ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, java.lang.Long duration, java.lang.String imageUrl, java.lang.String premiere,
            java.lang.String credits, java.lang.String episodeNumber, java.lang.Boolean recordable,
            ru.cti.oss.iptv.resource.logical.BtvChannel channel) {
        setName(name);
        setDescription(description);
        setStatus(status);
        setTimeFrame(timeFrame);
        setDuration(duration);
        setImageUrl(imageUrl);
        setPremiere(premiere);
        setCredits(credits);
        setEpisodeNumber(episodeNumber);
        setRecordable(recordable);
        
        setChannel(channel);
    }
    
    // -------- Attribute Accessors ----------
    
    /**
     * Get the timeFrame property.
     *
     * @return ru.cti.oss.cbe.datatypes.TimePeriod The value of timeFrame
     */
    @javax.persistence.Embedded
    @javax.persistence.AttributeOverrides( {
            @javax.persistence.AttributeOverride(name = "startTime", column = @javax.persistence.Column(name = "TIME_FRAME_START_TIME", insertable = true, updatable = true)),
            @javax.persistence.AttributeOverride(name = "endTime", column = @javax.persistence.Column(name = "TIME_FRAME_END_TIME", insertable = true, updatable = true)) })
    public ru.cti.oss.cbe.datatypes.TimePeriod getTimeFrame() {
        return timeFrame;
    }
    
    /**
     * Set the timeFrame property.
     * @param value the new value
     */
    public void setTimeFrame(ru.cti.oss.cbe.datatypes.TimePeriod value) {
        this.timeFrame = value;
    }
    
    /**
     * Get the duration property.
     *
     * @return java.lang.Long The value of duration
     */
    @javax.persistence.Column(name = "DURATION", nullable = false, insertable = true, updatable = true)
    @Index(name = "duration_index")
    public java.lang.Long getDuration() {
        return duration;
    }
    
    /**
     * Set the duration property.
     * @param value the new value
     */
    public void setDuration(java.lang.Long value) {
        this.duration = value;
    }
    
    /**
     * Get the imageUrl property.
     *
     * @return java.lang.String The value of imageUrl
     */
    @javax.persistence.Column(name = "IMAGE_URL", insertable = true, updatable = true)
    @Index(name = "image_url_index")
    public java.lang.String getImageUrl() {
        return imageUrl;
    }
    
    /**
     * Set the imageUrl property.
     * @param value the new value
     */
    public void setImageUrl(java.lang.String value) {
        this.imageUrl = value;
    }
    
    /**
     * Get the premiere property.
     *
     * @return java.lang.String The value of premiere
     */
    @javax.persistence.Column(name = "PREMIERE", insertable = true, updatable = true)
    public java.lang.String getPremiere() {
        return premiere;
    }
    
    /**
     * Set the premiere property.
     * @param value the new value
     */
    public void setPremiere(java.lang.String value) {
        this.premiere = value;
    }
    
    /**
     * Get the credits property.
     *
     * @return java.lang.String The value of credits
     */
    @javax.persistence.Column(name = "CREDITS", insertable = true, updatable = true)
    @Index(name = "credits_index")
    public java.lang.String getCredits() {
        return credits;
    }
    
    /**
     * Set the credits property.
     * @param value the new value
     */
    public void setCredits(java.lang.String value) {
        this.credits = value;
    }
    
    /**
     * Get the episodeNumber property.
     *
     * @return java.lang.String The value of episodeNumber
     */
    @javax.persistence.Column(name = "EPISODE_NUMBER", insertable = true, updatable = true)
    public java.lang.String getEpisodeNumber() {
        return episodeNumber;
    }
    
    /**
     * Set the episodeNumber property.
     * @param value the new value
     */
    public void setEpisodeNumber(java.lang.String value) {
        this.episodeNumber = value;
    }
    
    /**
     * Get the recordable property.
     *
     * @return java.lang.Boolean The value of recordable
     */
    @javax.persistence.Column(name = "RECORDABLE", insertable = true, updatable = true)
    public java.lang.Boolean getRecordable() {
        return recordable;
    }
    
    /**
     * Set the recordable property.
     * @param value the new value
     */
    public void setRecordable(java.lang.Boolean value) {
        this.recordable = value;
    }
    
    // ------------- Relations ------------------
    
    /**
     * Get the channel
     *
     * @return ru.cti.oss.iptv.resource.logical.BtvChannel
     */
    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "CHANNEL")
    public ru.cti.oss.iptv.resource.logical.BtvChannel getChannel() {
        return this.channel;
    }
    
    /**
     * Set the channel
     *
     * @param channel
     */
    public void setChannel(ru.cti.oss.iptv.resource.logical.BtvChannel channel) {
        this.channel = channel;
    }
    
    /* (non-Javadoc)
     * @see ru.cti.oss.iptv.resource.logical.MediaContent#getMediaSource()
     */
    @Deprecated
    @javax.persistence.Transient
    public ru.cti.oss.iptv.resource.logical.MediaSource getMediaSource() {
    	return MediaContentToDefaultMediaSourceHelper.getDefaultMediaAsset(this.getMediaSources());
    }
    
    // -------- Common Methods -----------
    
    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof Program)) {
            return false;
        }
        final Program that = (Program) object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId())) {
            return false;
        }
        return true;
    }
    
    /**
     * Get the cachedName property.
     * 
     * @return java.lang.String The value of cachedName
     */
    @javax.persistence.Column(name = "CACHED_NAME", length = 3800, insertable = true, updatable = true)
    public java.lang.String getCachedName() {
        return cachedName;
    }
    
    /**
     * Set the cachedName property.
     * @param value the new value
     */
    public void setCachedName(java.lang.String value) {
        this.cachedName = value;
    }
    
    /**
     * TRANSIENT fields ======================================================================================
     */
    
    private boolean selected;
    
    @Transient
    public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

    
    /**
     * COMMON methods =======================================================================================
     */
    
    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode() {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());
        
        return hashCode;
    }
    
    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Program(=");
        sb.append(super.toString());
        sb.append("timeFrame: ");
        if (getTimeFrame() != null)
            sb.append(getTimeFrame().toString());
        else
            sb.append("null");
        sb.append(", duration: ");
        sb.append(getDuration());
        sb.append(", imageUrl: ");
        sb.append(getImageUrl());
        sb.append(", premiere: ");
        sb.append(getPremiere());
        sb.append(", credits: ");
        sb.append(getCredits());
        sb.append(", episodeNumber: ");
        sb.append(getEpisodeNumber());
        sb.append(", recordable: ");
        sb.append(getRecordable());
        sb.append(")");
        return sb.toString();
    }

    @javax.persistence.Column(name = "CAT_NAME", length = 100, insertable = true, updatable = true)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}
	
	
		
	@javax.persistence.Column(name = "CAT_CODE", length = 100, insertable = true, updatable = true)
	public String getCategoryCode() {
		return categoryCode;
	}
	
	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}
	
	

	@javax.persistence.Column(name = "DIRECTOR", length = 255, insertable = true, updatable = true)
	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@javax.persistence.Column(name = "ACTOR", length = 255, insertable = true, updatable = true)
	public String getActor() {
		return actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}
	
	@javax.persistence.Column(name = "COUNTRY", length = 100, insertable = true, updatable = true)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@javax.persistence.Column(name = "RATING_ADD", length = 10, insertable = true, updatable = true)
	public String getRatingAdd() {
		return ratingAdd;
	}

	public void setRatingAdd(String ratingAdd) {
		this.ratingAdd = ratingAdd;
	}

	@javax.persistence.Column(name = "PRESENTER", length = 255, insertable = true, updatable = true)
	public String getPresenter() {
		return presenter;
	}

	public void setPresenter(String presenter) {
		this.presenter = presenter;
	}
    
}