// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.iptv.resource.physical;

/**
 * Autogenerated enumeration CasServerType.
 *
 * 
 */
public enum CasServerType implements java.io.Serializable
{
    /**
     *  
     */
    UNKNOWN,

    /**
     *  
     */
    VERIMATRIX;

    /**
     * CasServerType constructor
     */
    private CasServerType()
    {
    }

    /**
     * Return the CasServerType from a string value
     * @return CasServerType enum object
     */
    public static CasServerType fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}