// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.iptv.resource.physical;

/**
 * Autogenerated enumeration VideoServerType.
 */
public enum VideoServerType implements java.io.Serializable {
    /**
     *
     */
    UNKNOWN,

    /**
     *
     */
    KASENNA_8_1,

    /**
     *
     */
    KASENNA_8_2,

    /**
     *
     */
    KASENNA_8_3,

    KASENNA_9_1,

    WOWZA,

    NCUBE;

    /**
     * VideoServerType constructor
     */
    private VideoServerType() {
    }

    /**
     * Return the VideoServerType from a string value
     *
     * @return VideoServerType enum object
     */
    public static VideoServerType fromString(java.lang.String value) {
        return valueOf(value);
    }

    /**
     * Return a Collection of all literal values for this enumeration
     *
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals() {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++) {
            literals.add(values()[i].name());
        }
        return literals;
    }
}