// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.cbe.party;

/**
 * Autogenerated POJO EJB class for ContentProvider containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "CONTENT_PROVIDER")
@javax.persistence.NamedQuery(name = "ContentProvider.findAll", query = "select contentProvider from ContentProvider AS contentProvider")
public class ContentProvider
    extends ru.cti.oss.cbe.party.PartyRole
    implements java.io.Serializable
{

    private static final long serialVersionUID = -555637080803575949L;
    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public ContentProvider() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param validFor Value for the validFor property
     */
    public ContentProvider(java.lang.String name, ru.cti.oss.cbe.datatypes.TimePeriod validFor)
    {
        super(name, validFor);
        setName(name);
        setValidFor(validFor);
    }



    // ------------- Relations ------------------

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof ContentProvider))
        {
            return false;
        }
        final ContentProvider that = (ContentProvider)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        return super.toString();
    }

}