// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.cbe.party;

/**
 * Autogenerated enumeration Gender.
 *
 * 
 */
public enum Gender implements java.io.Serializable
{
    /**
     *  
     */
    MALE,

    /**
     *  
     */
    FEMALE;

    /**
     * Gender constructor
     */
    private Gender()
    {
    }

    /**
     * Return the Gender from a string value
     * @return Gender enum object
     */
    public static Gender fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}