// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.cbe.datatypes;

/**The Class <code>MessagePriority</code> present priority of message
 *	<p>
 *  <b>Copyright: </b>Copyright (c) 2009
 *  </p>
 *	<p>
 *   <b>Company: </b>CTI
 *  </p>
 *
 *	@author e.batogov <br/> <b>e-mail</b>: e.batogov@cti.ru <br/>
 *	@version 1.0
*/
public enum MessagePriority implements java.io.Serializable {
    
    HIGH, MEDIUM, LOW;
    
    /**
     * MessagePriority constructor
     */
    private MessagePriority() {
    }
    
    /**
     * Return the MessagePriority from a string value
     * @return MessagePriority enum object
     */
    public static MessagePriority fromString(java.lang.String value) {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals() {
        final java.util.Collection < String > literals = new java.util.ArrayList < String >(values().length);
        for (int i = 0; i < values().length; i++) {
            literals.add(values()[i].name());
        }
        return literals;
    }
}