// license-header java merge-point
/* Autogenerated by AndroMDA (Enumeration.vsl) - do not edit */
package ru.cti.oss.iptv.resource.logical;

/**
 * Autogenerated enumeration NvodShowStatus.
 *
 * 
 */
public enum NvodShowStatus implements java.io.Serializable
{
    /**
     *  
     */
    PENDING,

    /**
     *  
     */
    SCHEDULED,

    /**
     *  
     */
    EXPIRED;

    /**
     * NvodShowStatus constructor
     */
    private NvodShowStatus()
    {
    }

    /**
     * Return the NvodShowStatus from a string value
     * @return NvodShowStatus enum object
     */
    public static NvodShowStatus fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}