// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

import org.hibernate.annotations.Index;

/**
 * Autogenerated POJO EJB class for MovieCategory containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "MOVIE_CATEGORY")
@javax.persistence.NamedQueries( {
        @javax.persistence.NamedQuery(name = "MovieCategory.findAll", query = "select movieCategory from MovieCategory AS movieCategory"),
        @javax.persistence.NamedQuery(name = "MovieCategory.findByName", query = "select movieCategory from MovieCategory AS movieCategory where movieCategory.name=:name") })
public class MovieCategory implements java.io.Serializable, Comparable < MovieCategory >
{
    
    private static final long serialVersionUID = -4082671450471321728L;
    
    // ----------- Attribute Definitions ------------
    
    private java.lang.String name;
    private java.lang.String description;
    private java.lang.Long id;
    private java.lang.String externalId;
    
    // --------- Relationship Definitions -----------
    
    private java.util.Set < ru.cti.oss.iptv.resource.logical.Movie > movies = new java.util.TreeSet < ru.cti.oss.iptv.resource.logical.Movie >();
    
    // ---- Manageable Display Attributes (Transient) -----
    
    // --------------- Constructors -----------------
    
    /**
     * Default empty constructor
     */
    public MovieCategory() {
    }
    
    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     */
    public MovieCategory(java.lang.String name, java.lang.String description) {
        setName(name);
        setDescription(description);
    }
    
    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param movies Value for the movies relation
     */
    public MovieCategory(java.lang.String name, java.lang.String description,
            java.util.Set < ru.cti.oss.iptv.resource.logical.Movie > movies) {
        setName(name);
        setDescription(description);
        
        setMovies(movies);
    }
    
    // -------- Attribute Accessors ----------
    
    /**
     * Get the externalId property.
     * 
     * @return java.lang.String The value of externalId
     */
    @javax.persistence.Column(name = "EXTERNAL_ID", unique = false, nullable = true, insertable = true, updatable = true)
    public java.lang.String getExternalId() {
        return this.externalId;
    }
    
    /**
     * Set the externalId property.
     * @param value the new value
     */
    public void setExternalId(final java.lang.String value) {
        this.externalId = value;
    }
    
    /**
     * Get the name property.
     * 
     * @return java.lang.String The value of name
     */
    @javax.persistence.Column(name = "NAME", nullable = false, insertable = true, updatable = true)
    @Index(name = "name_index")
    public java.lang.String getName() {
        return name;
    }
    
    /**
     * Set the name property.
     * @param value the new value
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }
    
    /**
     * Get the description property.
     * 
     * @return java.lang.String The value of description
     */
    @javax.persistence.Column(name = "DESCRIPTION", insertable = true, updatable = true, length = 3800)
    public java.lang.String getDescription() {
        return description;
    }
    
    /**
     * Set the description property.
     * @param value the new value
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }
    
    /**
     * Get the id property.
     * 
     * @return java.lang.Long The value of id
     */
    @javax.persistence.Id
    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Column(name = "ID", nullable = false, insertable = true, updatable = true)
    @Index(name = "id_index")
    public java.lang.Long getId() {
        return id;
    }
    
    /**
     * Set the id property.
     * @param value the new value
     */
    public void setId(java.lang.Long value) {
        this.id = value;
    }
    
    // ------------- Relations ------------------
    
    /**
     * Get the movies Collection
     *
     * @return java.util.Set<ru.cti.oss.iptv.resource.logical.Movie>
     */
    @javax.persistence.OneToMany(mappedBy = "movieCategory", fetch = javax.persistence.FetchType.LAZY)
    public java.util.Set < ru.cti.oss.iptv.resource.logical.Movie > getMovies() {
        return this.movies;
    }
    
    /**
     * Set the movies
     *
     * @param movies
     */
    public void setMovies(java.util.Set < ru.cti.oss.iptv.resource.logical.Movie > movies) {
        this.movies = movies;
    }
    
    /**
     * Add to movies
     *
     * @param movie
     */
    
    public void addToMovies(ru.cti.oss.iptv.resource.logical.Movie movie) {
        if (movie == null)
            return;
        this.getMovies().add(movie);
        movie.setMovieCategory(this);
    }
    
    /**
     * Remove from movies
     *
     * @param movie
     */
    
    public void removeFromMovies(ru.cti.oss.iptv.resource.logical.Movie movie) {
        if (movie == null)
            return;
        this.getMovies().remove(movie);
        movie.setMovieCategory(null);
    }
    
    // -------- Common Methods -----------
    
    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof MovieCategory)) {
            return false;
        }
        final MovieCategory that = (MovieCategory) object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId())) {
            return false;
        }
        return true;
    }
    
    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode() {
        int hashCode = 0;
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());
        
        return hashCode;
    }
    
    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("MovieCategory(=");
        sb.append("name: ");
        sb.append(getName());
        sb.append(", description: ");
        sb.append(getDescription());
        sb.append(", id: ");
        sb.append(getId());
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * @see java.lang.Comparable#compareTo(T)
     */
    public int compareTo(MovieCategory o) {
        int cmp = 0;
        if (this.getId() != null) {
            cmp = this.getId().compareTo(o.getId());
        } else {
            if (this.getName() != null) {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(o.getName()));
            }
            if (this.getDescription() != null) {
                cmp = (cmp != 0 ? cmp : this.getDescription().compareTo(o.getDescription()));
            }
        }
        return cmp;
    }
}