// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

import org.hibernate.annotations.Index;

/**
 * Autogenerated POJO EJB class for SubtitleChannel containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "SUBTITLE_CHANNEL")
@javax.persistence.NamedQuery(name = "SubtitleChannel.findAll", query = "select subtitleChannel from SubtitleChannel AS subtitleChannel")
public class SubtitleChannel implements java.io.Serializable, Comparable < SubtitleChannel >
{
    
    private static final long serialVersionUID = 5915899434969459508L;
    
    // ----------- Attribute Definitions ------------
    
    private java.lang.String name;
    private java.lang.Long pid;
    private java.lang.Long id;
    
    // --------- Relationship Definitions -----------
    
    private ru.cti.oss.cbe.location.Locale locale;
    private ru.cti.oss.iptv.resource.logical.MediaSource mediaSource;
    
    // ---- Manageable Display Attributes (Transient) -----
    
    // --------------- Constructors -----------------
    
    /**
     * Default empty constructor
     */
    public SubtitleChannel() {
    }
    
    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param pid Value for the pid property
     */
    public SubtitleChannel(java.lang.String name, java.lang.Long pid) {
        setName(name);
        setPid(pid);
    }
    
    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param pid Value for the pid property
     * @param locale Value for the locale relation
     * @param mediaSource Value for the mediaSource relation
     */
    public SubtitleChannel(java.lang.String name, java.lang.Long pid, ru.cti.oss.cbe.location.Locale locale,
            ru.cti.oss.iptv.resource.logical.MediaSource mediaSource) {
        setName(name);
        setPid(pid);
        
        setLocale(locale);
        setMediaSource(mediaSource);
    }
    
    // -------- Attribute Accessors ----------
    
    /**
     * Get the name property.
     * 
     * @return java.lang.String The value of name
     */
    @javax.persistence.Column(name = "NAME", nullable = false, insertable = true, updatable = true)
    @Index(name = "name_index")
    public java.lang.String getName() {
        return name;
    }
    
    /**
     * Set the name property.
     * @param value the new value
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }
    
    /**
     * Get the pid property.
     * 
     * @return java.lang.Long The value of pid
     */
    @javax.persistence.Column(name = "PID", nullable = false, insertable = true, updatable = true)
    @Index(name = "pid_index")
    public java.lang.Long getPid() {
        return pid;
    }
    
    /**
     * Set the pid property.
     * @param value the new value
     */
    public void setPid(java.lang.Long value) {
        this.pid = value;
    }
    
    /**
     * Get the id property.
     * 
     * @return java.lang.Long The value of id
     */
    @javax.persistence.Id
    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Column(name = "ID", nullable = false, insertable = true, updatable = true)
    @Index(name = "id_index")
    public java.lang.Long getId() {
        return id;
    }
    
    /**
     * Set the id property.
     * @param value the new value
     */
    public void setId(java.lang.Long value) {
        this.id = value;
    }
    
    // ------------- Relations ------------------
    
    /**
     * Get the locale
     *
     * @return ru.cti.oss.cbe.location.Locale
     */
    @javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "LOCALE")
    @Index(name = "locale_index")
    public ru.cti.oss.cbe.location.Locale getLocale() {
        return this.locale;
    }
    
    /**
     * Set the locale
     *
     * @param locale
     */
    public void setLocale(ru.cti.oss.cbe.location.Locale locale) {
        this.locale = locale;
    }
    
    /**
     * Get the mediaSource
     *
     * @return ru.cti.oss.iptv.resource.logical.MediaSource
     */
    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "MEDIASOURCE")
    public ru.cti.oss.iptv.resource.logical.MediaSource getMediaSource() {
        return this.mediaSource;
    }
    
    /**
     * Set the mediaSource
     *
     * @param mediaSource
     */
    public void setMediaSource(ru.cti.oss.iptv.resource.logical.MediaSource mediaSource) {
        this.mediaSource = mediaSource;
    }
    
    // -------- Common Methods -----------
    
    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof SubtitleChannel)) {
            return false;
        }
        final SubtitleChannel that = (SubtitleChannel) object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId())) {
            return false;
        }
        return true;
    }
    
    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode() {
        int hashCode = 0;
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());
        
        return hashCode;
    }
    
    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("SubtitleChannel(=");
        sb.append("name: ");
        sb.append(getName());
        sb.append(", pid: ");
        sb.append(getPid());
        sb.append(", id: ");
        sb.append(getId());
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * @see java.lang.Comparable#compareTo(T)
     */
    public int compareTo(SubtitleChannel o) {
        int cmp = 0;
        if (this.getId() != null) {
            cmp = this.getId().compareTo(o.getId());
        } else {
            if (this.getName() != null) {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(o.getName()));
            }
            if (this.getPid() != null) {
                cmp = (cmp != 0 ? cmp : this.getPid().compareTo(o.getPid()));
            }
        }
        return cmp;
    }
}