// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.cbe.party;

/**
 * Autogenerated POJO EJB class for Organization containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "ORGANIZATION")
@javax.persistence.NamedQuery(name = "Organization.findAll", query = "select organization from Organization AS organization")
public class Organization
    extends ru.cti.oss.cbe.party.Party
    implements java.io.Serializable
{

    private static final long serialVersionUID = -8434760411374649609L;

    // ----------- Attribute Definitions ------------

    private java.lang.String tradeName;

    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public Organization() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param externalId Value for the externalId property
     * @param tradeName Value for the tradeName property
     */
    public Organization(java.lang.String name, java.lang.String externalId, java.lang.String tradeName)
    {
        super(name, externalId);
        setName(name);
        setExternalId(externalId);
        setTradeName(tradeName);
    }



    // -------- Attribute Accessors ----------

    /**
     * Get the tradeName property.
     * 
     * @return java.lang.String The value of tradeName
     */
    	@javax.persistence.Column(name = "TRADE_NAME", nullable = false, insertable = true, updatable = true)
    public java.lang.String getTradeName()
    {
        return tradeName;
    }

    /**
     * Set the tradeName property.
     * @param value the new value
     */
    public void setTradeName(java.lang.String value)
    {
        this.tradeName = value;
    }


    // ------------- Relations ------------------

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Organization))
        {
            return false;
        }
        final Organization that = (Organization)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("Organization(=");
        sb.append(super.toString());
        sb.append("tradeName: ");
        sb.append(getTradeName());
        sb.append(")");
        return sb.toString();
    }

}