// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

/**
 * Autogenerated POJO EJB class for RadioProgram containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "RADIO_PROGRAM")
@javax.persistence.NamedQueries
({
    @javax.persistence.NamedQuery(name = "RadioProgram.findAll", query = "select radioProgram from RadioProgram AS radioProgram"),
    @javax.persistence.NamedQuery(name = "RadioProgram.findByRadioChannel", query = "from RadioProgram p where p.radioChannel.id = :radioChannelId order by p.timeFrame.startTime"), 
    @javax.persistence.NamedQuery(name = "RadioProgram.findByTime", query = "from RadioProgram p where p.radioChannel.id = :radioChannelId and :startTime between p.timeFrame.startTime and p.timeFrame.endTime"), 
    @javax.persistence.NamedQuery(name = "RadioProgram.findByTimeFrame", query = "from RadioProgram p where p.radioChannel.id = :radioChannelId and p.timeFrame.startTime >= :startTime and p.timeFrame.endTime <= :endTime order by p.timeFrame.startTime")
})
public class RadioProgram
    extends ru.cti.oss.iptv.resource.logical.MediaContent
    implements java.io.Serializable
{

    private static final long serialVersionUID = -4257054848119272448L;

    // ----------- Attribute Definitions ------------

    private ru.cti.oss.cbe.datatypes.TimePeriod timeFrame = new ru.cti.oss.cbe.datatypes.TimePeriod();
    private java.lang.Long duration;
    private java.lang.String credits;


    // --------- Relationship Definitions -----------

    private ru.cti.oss.iptv.resource.logical.RadioChannel radioChannel;

    // ---- Manageable Display Attributes (Transient) -----


    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public RadioProgram() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param timeFrame Value for the timeFrame property
     * @param duration Value for the duration property
     * @param credits Value for the credits property
     */
    public RadioProgram(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, java.lang.Long duration, java.lang.String credits)
    {
        super(name, description, status);
        setName(name);
        setDescription(description);
        setStatus(status);
        setTimeFrame(timeFrame);
        setDuration(duration);
        setCredits(credits);
    }

    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param timeFrame Value for the timeFrame property
     * @param duration Value for the duration property
     * @param credits Value for the credits property
     * @param radioChannel Value for the radioChannel relation
     */
    public RadioProgram(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, java.lang.Long duration, java.lang.String credits, ru.cti.oss.iptv.resource.logical.RadioChannel radioChannel)
    {
        setName(name);
        setDescription(description);
        setStatus(status);
        setTimeFrame(timeFrame);
        setDuration(duration);
        setCredits(credits);

        setRadioChannel(radioChannel);
    }


    // -------- Attribute Accessors ----------

    /**
     * Get the timeFrame property.
     * 
     * @return ru.cti.oss.cbe.datatypes.TimePeriod The value of timeFrame
     */
    @javax.persistence.Embedded
    @javax.persistence.AttributeOverrides
    ({
        @javax.persistence.AttributeOverride(name = "startTime", column = @javax.persistence.Column(name = "TIME_FRAME_START_TIME", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "endTime", column = @javax.persistence.Column(name = "TIME_FRAME_END_TIME", insertable = true, updatable = true))
    })
    public ru.cti.oss.cbe.datatypes.TimePeriod getTimeFrame()
    {
        return timeFrame;
    }

    /**
     * Set the timeFrame property.
     * @param value the new value
     */
    public void setTimeFrame(ru.cti.oss.cbe.datatypes.TimePeriod value)
    {
        this.timeFrame = value;
    }

    /**
     * Get the duration property.
     * 
     * @return java.lang.Long The value of duration
     */
    	@javax.persistence.Column(name = "DURATION", nullable = false, insertable = true, updatable = true)
    public java.lang.Long getDuration()
    {
        return duration;
    }

    /**
     * Set the duration property.
     * @param value the new value
     */
    public void setDuration(java.lang.Long value)
    {
        this.duration = value;
    }

    /**
     * Get the credits property.
     * 
     * @return java.lang.String The value of credits
     */
    	@javax.persistence.Column(name = "CREDITS", insertable = true, updatable = true)
    public java.lang.String getCredits()
    {
        return credits;
    }

    /**
     * Set the credits property.
     * @param value the new value
     */
    public void setCredits(java.lang.String value)
    {
        this.credits = value;
    }


    // ------------- Relations ------------------

    /**
     * Get the radioChannel
     *
     * @return ru.cti.oss.iptv.resource.logical.RadioChannel
     */
    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "RADIOCHANNEL")
    public ru.cti.oss.iptv.resource.logical.RadioChannel getRadioChannel()
    {
        return this.radioChannel;
    }

   /**
    * Set the radioChannel
    *
    * @param radioChannel
    */
    public void setRadioChannel(ru.cti.oss.iptv.resource.logical.RadioChannel radioChannel)
    {
        this.radioChannel = radioChannel;
    }
    
    /* (non-Javadoc)
     * @see ru.cti.oss.iptv.resource.logical.MediaContent#getMediaSource()
     */
    @Deprecated
    @javax.persistence.Transient
    public ru.cti.oss.iptv.resource.logical.MediaSource getMediaSource() {
    	return MediaContentToDefaultMediaSourceHelper.getDefaultMediaAsset(this.getMediaSources());
    }


    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof RadioProgram))
        {
            return false;
        }
        final RadioProgram that = (RadioProgram)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("RadioProgram(=");
        sb.append(super.toString());
        sb.append("timeFrame: ");
		if (getTimeFrame()!=null)
		    sb.append(getTimeFrame().toString());
	    else
		    sb.append("null");
        sb.append(", duration: ");
        sb.append(getDuration());
        sb.append(", credits: ");
        sb.append(getCredits());
        sb.append(")");
        return sb.toString();
    }

}