// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

import javax.persistence.NamedQuery;

/**
 * Autogenerated POJO EJB class for RadioChannel containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "RADIO_CHANNEL")
@javax.persistence.NamedQueries
({
   @NamedQuery(name = "RadioChannel.findAll", query = "select radioChannel from RadioChannel as radioChannel order by radioChannel.id"),
   @NamedQuery(name = "RadioChannel.findAllIds", query = "select radioChannel.id from RadioChannel as radioChannel order by radioChannel.id"),
   @NamedQuery(name = "RadioChannel.findAllLogo", query = "select radioChannel.id, radioChannel.logo from RadioChannel as radioChannel order by radioChannel.id"),
   @NamedQuery(name = "RadioChannel.findLogoById", query = "select radioChannel.logo from RadioChannel as radioChannel where radioChannel.id =:id")
})
public class RadioChannel
    extends ru.cti.oss.iptv.resource.logical.MediaContent
    implements java.io.Serializable
{

    private static final long serialVersionUID = 9011874635440648905L;
    
    private String channelUrl;
    
    /**
	 * @return the channelUrl
	 */
	@javax.persistence.Column(name = "CHANNEL_URL", insertable = true, updatable = true)
	public String getChannelUrl() {
		return channelUrl;
	}

	/**
	 * @param channelUrl the channelUrl to set
	 */
	public void setChannelUrl(String channelUrl) {
		this.channelUrl = channelUrl;
	}

    // ----------- Attribute Definitions ------------

    private ru.cti.oss.iptv.Image logo = new ru.cti.oss.iptv.Image();
    private java.lang.Integer sortOrder;

    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public RadioChannel() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param logo Value for the logo property
     * @param sortOrder Value for the sortOrder property
     */
    public RadioChannel(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, ru.cti.oss.iptv.Image logo, java.lang.Integer sortOrder)
    {
        super(name, description, status);
        setName(name);
        setDescription(description);
        setStatus(status);
        setLogo(logo);
        setSortOrder(sortOrder);
    }



    // -------- Attribute Accessors ----------

    /**
     * Get the logo property.
     * 
     * @return ru.cti.oss.iptv.Image The value of logo
     */
    @javax.persistence.Embedded
    @javax.persistence.AttributeOverrides
    ({
        @javax.persistence.AttributeOverride(name = "width", column = @javax.persistence.Column(name = "LOGO_WIDTH", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "height", column = @javax.persistence.Column(name = "LOGO_HEIGHT", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "size", column = @javax.persistence.Column(name = "LOGO_SIZE", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "contentType", column = @javax.persistence.Column(name = "LOGO_CONTENT_TYPE", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "data", column = @javax.persistence.Column(name = "LOGO_DATA", insertable = true, updatable = true))
    })
    public ru.cti.oss.iptv.Image getLogo()
    {
        return logo;
    }

    /**
     * Set the logo property.
     * @param value the new value
     */
    public void setLogo(ru.cti.oss.iptv.Image value)
    {
        this.logo = value;
    }

    /**
     * Get the sortOrder property.
     * 
     * @return java.lang.Integer The value of sortOrder
     */
    	@javax.persistence.Column(name = "SORT_ORDER", nullable = false, insertable = true, updatable = true)
    public java.lang.Integer getSortOrder()
    {
        return sortOrder;
    }

    /**
     * Set the sortOrder property.
     * @param value the new value
     */
    public void setSortOrder(java.lang.Integer value)
    {
        this.sortOrder = value;
    }

    /* (non-Javadoc)
     * @see ru.cti.oss.iptv.resource.logical.MediaContent#getMediaSource()
     */
    @Deprecated
    @javax.persistence.Transient
    public ru.cti.oss.iptv.resource.logical.MediaSource getMediaSource() {
		return MediaContentToDefaultMediaSourceHelper.getDefaultMulticastChannel(this.getMediaSources());
    }

    // ------------- Relations ------------------

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof RadioChannel))
        {
            return false;
        }
        final RadioChannel that = (RadioChannel)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("RadioChannel(=");
        sb.append(super.toString());
        sb.append("logo: ");
		if (getLogo()!=null)
		    sb.append(getLogo().toString());
	    else
		    sb.append("null");
        sb.append(", sortOrder: ");
        sb.append(getSortOrder());
        sb.append(")");
        return sb.toString();
    }

}