// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.physical;

/**
 * Autogenerated POJO EJB class for CasServer containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "CAS_SERVER")
@javax.persistence.NamedQueries
({
    @javax.persistence.NamedQuery(name = "CasServer.findAll", query = "select casServer from CasServer AS casServer"),
    @javax.persistence.NamedQuery(name = "CasServer.findByStatus", query = "from CasServer as casServer where casServer.status = :status")
})
public class CasServer
    extends ru.cti.oss.iptv.resource.physical.Server
    implements java.io.Serializable
{

    private static final long serialVersionUID = 726072349939419458L;

    // ----------- Attribute Definitions ------------

    private ru.cti.oss.iptv.resource.physical.CasServerType type;
    private java.lang.Long port;

    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public CasServer() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param availabilityStatus Value for the availabilityStatus property
     * @param hostname Value for the hostname property
     * @param type Value for the type property
     * @param port Value for the port property
     */
    public CasServer(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, ru.cti.oss.cbe.datatypes.AvailabilityStatus availabilityStatus, java.lang.String hostname, ru.cti.oss.iptv.resource.physical.CasServerType type, java.lang.Long port)
    {
        super(name, description, status, availabilityStatus, hostname);
        setName(name);
        setDescription(description);
        setStatus(status);
        setAvailabilityStatus(availabilityStatus);
        setHostname(hostname);
        setType(type);
        setPort(port);
    }



    // -------- Attribute Accessors ----------

    /**
     * Get the type property.
     * 
     * @return ru.cti.oss.iptv.resource.physical.CasServerType The value of type
     */
    	@javax.persistence.Column(name = "TYPE", insertable = true, updatable = true)
    @javax.persistence.Enumerated(javax.persistence.EnumType.ORDINAL)
    public ru.cti.oss.iptv.resource.physical.CasServerType getType()
    {
        return type;
    }

    /**
     * Set the type property.
     * @param value the new value
     */
    public void setType(ru.cti.oss.iptv.resource.physical.CasServerType value)
    {
        this.type = value;
    }

    /**
     * Get the port property.
     * 
     * @return java.lang.Long The value of port
     */
    	@javax.persistence.Column(name = "PORT", insertable = true, updatable = true)
    public java.lang.Long getPort()
    {
        return port;
    }

    /**
     * Set the port property.
     * @param value the new value
     */
    public void setPort(java.lang.Long value)
    {
        this.port = value;
    }


    // ------------- Relations ------------------

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CasServer))
        {
            return false;
        }
        final CasServer that = (CasServer)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("CasServer(=");
        sb.append(super.toString());
        sb.append("type: ");
        sb.append(getType());
        sb.append(", port: ");
        sb.append(getPort());
        sb.append(")");
        return sb.toString();
    }

}