// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.notification;

import org.hibernate.annotations.Index;

/**
 * Autogenerated POJO EJB class for CustomerNotification containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "CUSTOMER_NOTIFICATION")
@javax.persistence.NamedQueries( {
        @javax.persistence.NamedQuery(name = "CustomerNotification.findAll", query = "select customerNotification from CustomerNotification AS customerNotification"),
        @javax.persistence.NamedQuery(name = "CustomerNotification.findByAccount", query = "select cn from CustomerNotification cn where cn.customerAccount.id = :account"),
        @javax.persistence.NamedQuery(name = "CustomerNotification.findByAccountAndType", query = "select cn from CustomerNotification cn where cn.customerAccount.id = :account and cn.type = :type"),
        @javax.persistence.NamedQuery(name = "CustomerNotification.findByAccountAndTypeAndTimeFrame", query = "select cn from CustomerNotification cn where cn.customerAccount.id = :account and cn.type = :type"),
        @javax.persistence.NamedQuery(name = "CustomerNotification.findNotifications", query = "select cn from CustomerNotification cn where cn.customerAccount.id = :account and cn.type =  :type and cn.timeFrame.endTime > :current_date order by cn.timeFrame.startTime"),
        @javax.persistence.NamedQuery(name = "CustomerNotification.findByAccountAndTypeAndDate", query = "select cn from CustomerNotification cn where cn.customerAccount.id = :account and cn.type = :type "
                + " and cn.timeFrame.endTime> :date_par ") })
public class CustomerNotification implements java.io.Serializable, Comparable < CustomerNotification >
{
    
    private static final long serialVersionUID = -778542465495026191L;
    
    // ----------- Attribute Definitions ------------
    
    private java.lang.String name;
    private java.lang.String description;
    private short periodType;
    private short repeatPeriod;
    private ru.cti.oss.cbe.datatypes.TimePeriod timeFrame = new ru.cti.oss.cbe.datatypes.TimePeriod();
    private int type;
    private java.lang.String params;
    private java.lang.String btvChannelName;
    private java.lang.Long btvChannelId;
    private java.lang.Long id;
    
    // --------- Relationship Definitions -----------
    
    private ru.cti.oss.cbe.customer.CustomerAccount customerAccount;
    
    // ---- Manageable Display Attributes (Transient) -----
    
    // --------------- Constructors -----------------
    
    /**
     * Default empty constructor
     */
    public CustomerNotification() {
    }
    
    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param periodType Value for the periodType property
     * @param repeatPeriod Value for the repeatPeriod property
     * @param timeFrame Value for the timeFrame property
     * @param type Value for the type property
     * @param params Value for the params property
     */
    public CustomerNotification(java.lang.String name, java.lang.String description, short periodType, short repeatPeriod,
            ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, int type, java.lang.String params) {
        setName(name);
        setDescription(description);
        setPeriodType(periodType);
        setRepeatPeriod(repeatPeriod);
        setTimeFrame(timeFrame);
        setType(type);
        setParams(params);
    }
    
    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param periodType Value for the periodType property
     * @param repeatPeriod Value for the repeatPeriod property
     * @param timeFrame Value for the timeFrame property
     * @param type Value for the type property
     * @param params Value for the params property
     * @param customerAccount Value for the customerAccount relation
     */
    public CustomerNotification(java.lang.String name, java.lang.String description, short periodType, short repeatPeriod,
            ru.cti.oss.cbe.datatypes.TimePeriod timeFrame, int type, java.lang.String params,
            ru.cti.oss.cbe.customer.CustomerAccount customerAccount) {
        setName(name);
        setDescription(description);
        setPeriodType(periodType);
        setRepeatPeriod(repeatPeriod);
        setTimeFrame(timeFrame);
        setType(type);
        setParams(params);
        
        setCustomerAccount(customerAccount);
    }
    
    // -------- Attribute Accessors ----------
    
    /**
     * Get the name property.
     * 
     * @return java.lang.String The value of name
     */
    @javax.persistence.Column(name = "NAME", nullable = false, insertable = true, updatable = true)
    @Index(name = "name_index")
    public java.lang.String getName() {
        return name;
    }
    
    /**
     * Set the name property.
     * @param value the new value
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }
    
    /**
     * Get the description property.
     * 
     * @return java.lang.String The value of description
     */
    @javax.persistence.Column(name = "DESCRIPTION", insertable = true, updatable = true, length = 3800)
    public java.lang.String getDescription() {
        return description;
    }
    
    /**
     * Set the description property.
     * @param value the new value
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }
    
    /**
     * Get the periodType property.
     * 
     * @return short The value of periodType
     */
    @javax.persistence.Column(name = "PERIOD_TYPE", nullable = false, insertable = true, updatable = true)
    @Index(name = "period_type_index")
    public short getPeriodType() {
        return periodType;
    }
    
    /**
     * Set the periodType property.
     * @param value the new value
     */
    public void setPeriodType(short value) {
        this.periodType = value;
    }
    
    /**
     * Get the repeatPeriod property.
     * 
     * @return short The value of repeatPeriod
     */
    @javax.persistence.Column(name = "REPEAT_PERIOD", nullable = false, insertable = true, updatable = true)
    @Index(name = "repeat_period_index")
    public short getRepeatPeriod() {
        return repeatPeriod;
    }
    
    /**
     * Set the repeatPeriod property.
     * @param value the new value
     */
    public void setRepeatPeriod(short value) {
        this.repeatPeriod = value;
    }
    
    /**
     * Get the timeFrame property.
     * 
     * @return ru.cti.oss.cbe.datatypes.TimePeriod The value of timeFrame
     */
    @javax.persistence.Embedded
    @javax.persistence.AttributeOverrides( {
            @javax.persistence.AttributeOverride(name = "startTime", column = @javax.persistence.Column(name = "TIME_FRAME_START_TIME", insertable = true, updatable = true)),
            @javax.persistence.AttributeOverride(name = "endTime", column = @javax.persistence.Column(name = "TIME_FRAME_END_TIME", insertable = true, updatable = true)) })
    public ru.cti.oss.cbe.datatypes.TimePeriod getTimeFrame() {
        return timeFrame;
    }
    
    /**
     * Set the timeFrame property.
     * @param value the new value
     */
    public void setTimeFrame(ru.cti.oss.cbe.datatypes.TimePeriod value) {
        this.timeFrame = value;
    }
    
    /**
     * Get the type property.
     * 
     * @return int The value of type
     */
    @javax.persistence.Column(name = "TYPE", nullable = false, insertable = true, updatable = true)
    @Index(name = "type_index")
    public int getType() {
        return type;
    }
    
    /**
     * Set the type property.
     * @param value the new value
     */
    public void setType(int value) {
        this.type = value;
    }
    
    /**
     * Get the params property.
     * 
     * @return java.lang.String The value of params
     */
    @javax.persistence.Column(name = "PARAMS", nullable = false, insertable = true, updatable = true)
    @Index(name = "params_index")
    public java.lang.String getParams() {
        return params;
    }
    
    /**
     * Set the params property.
     * @param value the new value
     */
    public void setParams(java.lang.String value) {
        this.params = value;
    }
    
    /**
     * Get the id property.
     * 
     * @return java.lang.Long The value of id
     */
    @javax.persistence.Id
    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Column(name = "ID", nullable = false, insertable = true, updatable = true)
    @Index(name = "id_index")
    public java.lang.Long getId() {
        return id;
    }
    
    /**
     * Set the id property.
     * @param value the new value
     */
    public void setId(java.lang.Long value) {
        this.id = value;
    }
    
    // ------------- Relations ------------------
    
    /**
     * Get the customerAccount
     *
     * @return ru.cti.oss.cbe.customer.CustomerAccount
     */
    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY)
    @javax.persistence.JoinColumn(name = "CUSTOMERACCOUNT")
    public ru.cti.oss.cbe.customer.CustomerAccount getCustomerAccount() {
        return this.customerAccount;
    }
    
    /**
     * Set the customerAccount
     *
     * @param customerAccount
     */
    public void setCustomerAccount(ru.cti.oss.cbe.customer.CustomerAccount customerAccount) {
        this.customerAccount = customerAccount;
    }
    
    
    @javax.persistence.Column(name = "BTV_CHANNEL_ID", insertable = true, updatable = true)
    @Index(name = "btv_channel_id_index")
	public java.lang.Long getBtvChannelId() {
		return btvChannelId;
	}
    
    public void setBtvChannelId(java.lang.Long btvChannelId) {
		this.btvChannelId = btvChannelId;
	}

	public void setBtvChannelName(java.lang.String btvChannelName) {
		this.btvChannelName = btvChannelName;
	}

	@javax.persistence.Column(name = "BTV_CHANNEL_NAME", insertable = true, updatable = true)
	public java.lang.String getBtvChannelName() {
		return btvChannelName;
	}
    
    
    
    // -------- Common Methods -----------
    
    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof CustomerNotification)) {
            return false;
        }
        final CustomerNotification that = (CustomerNotification) object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId())) {
            return false;
        }
        return true;
    }
    
    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode() {
        int hashCode = 0;
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());
        
        return hashCode;
    }
    
    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("CustomerNotification(=");
        sb.append("name: ");
        sb.append(getName());
        sb.append(", description: ");
        sb.append(getDescription());
        sb.append(", periodType: ");
        sb.append(getPeriodType());
        sb.append(", repeatPeriod: ");
        sb.append(getRepeatPeriod());
        sb.append(", timeFrame: ");
        if (getTimeFrame() != null)
            sb.append(getTimeFrame().toString());
        else
            sb.append("null");
        sb.append(", type: ");
        sb.append(getType());
        sb.append(", params: ");
        sb.append(getParams());
        sb.append(", id: ");
        sb.append(getId());
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * @see java.lang.Comparable#compareTo(T)
     */
    public int compareTo(CustomerNotification o) {
        int cmp = 0;
        if (this.getId() != null) {
            cmp = this.getId().compareTo(o.getId());
        } else {
            if (this.getName() != null) {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(o.getName()));
            }
            if (this.getDescription() != null) {
                cmp = (cmp != 0 ? cmp : this.getDescription().compareTo(o.getDescription()));
            }
            if (this.getParams() != null) {
                cmp = (cmp != 0 ? cmp : this.getParams().compareTo(o.getParams()));
            }
        }
        return cmp;
    }
}